import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { roleGuard } from './core/guards/role.guard';

export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./layout/public-layout/public-layout').then((m) => m.PublicLayoutComponent),
    children: [
      { path: '', title: 'Home', loadComponent: () => import('./features/public/home/home').then((m) => m.HomeComponent) },
      { path: 'events', title: 'Events', data: { kind: 'events' }, loadComponent: () => import('./features/public/catalog/catalog').then((m) => m.CatalogComponent) },
      { path: 'events/:slug', title: 'Event Details', data: { kind: 'event' }, loadComponent: () => import('./features/public/detail/detail').then((m) => m.DetailComponent) },
      { path: 'venues', title: 'Venues', data: { kind: 'venues' }, loadComponent: () => import('./features/public/catalog/catalog').then((m) => m.CatalogComponent) },
      { path: 'venues/:slug', title: 'Venue Details', data: { kind: 'venue' }, loadComponent: () => import('./features/public/detail/detail').then((m) => m.DetailComponent) },
      { path: 'services', title: 'Services', data: { mode: 'services' }, loadComponent: () => import('./features/public/static-page/static-page').then((m) => m.StaticPageComponent) },
      { path: 'resources', title: 'Resources', data: { mode: 'resources' }, loadComponent: () => import('./features/public/static-page/static-page').then((m) => m.StaticPageComponent) },
      { path: 'about', title: 'About Us', data: { mode: 'about' }, loadComponent: () => import('./features/public/static-page/static-page').then((m) => m.StaticPageComponent) },
      { path: 'privacy', title: 'Privacy Policy', data: { kind: 'privacy' }, loadComponent: () => import('./features/public/legal/legal').then((m) => m.LegalComponent) },
      { path: 'terms', title: 'Terms', data: { kind: 'terms' }, loadComponent: () => import('./features/public/legal/legal').then((m) => m.LegalComponent) },
      { path: 'success', title: 'Success', loadComponent: () => import('./features/public/success/success').then((m) => m.SuccessComponent) },
    ],
  },
  { path: 'login', title: 'Login', loadComponent: () => import('./features/auth/login/login').then((m) => m.LoginComponent) },
  { path: 'register', title: 'Sign Up', loadComponent: () => import('./features/auth/register/register').then((m) => m.RegisterComponent) },
  { path: 'password-reset', title: 'Reset Password', loadComponent: () => import('./features/auth/password-reset/password-reset').then((m) => m.PasswordResetComponent) },
  { path: 'verify-email', title: 'Verify Email', loadComponent: () => import('./features/auth/verify-email/verify-email').then((m) => m.VerifyEmailComponent) },
  { path: 'access-denied', title: 'Access Denied', loadComponent: () => import('./features/public/access-denied/access-denied').then((m) => m.AccessDeniedComponent) },
  {
    path: 'customer',
    canActivate: [authGuard, roleGuard],
    data: { role: 'customer', roles: ['Customer'] },
    loadComponent: () => import('./layout/workspace-layout/workspace-layout').then((m) => m.WorkspaceLayoutComponent),
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', title: 'Customer Dashboard', loadComponent: () => import('./features/customer/dashboard/customer-dashboard').then((m) => m.CustomerDashboardComponent) },
      { path: 'browse-events', title: 'Browse Events', data: { kind: 'events', workspace: true, detailBase: '/customer/browse-events', backLink: '/customer/dashboard' }, loadComponent: () => import('./features/public/catalog/catalog').then((m) => m.CatalogComponent) },
      { path: 'browse-events/:slug', title: 'Event Details', data: { kind: 'event', backLink: '/customer/browse-events', eventsLink: '/customer/browse-events' }, loadComponent: () => import('./features/public/detail/detail').then((m) => m.DetailComponent) },
      { path: 'browse-venues', title: 'Browse Venues', data: { kind: 'venues', workspace: true, detailBase: '/customer/browse-venues', backLink: '/customer/dashboard' }, loadComponent: () => import('./features/public/catalog/catalog').then((m) => m.CatalogComponent) },
      { path: 'browse-venues/:slug', title: 'Venue Details', data: { kind: 'venue', backLink: '/customer/browse-venues', eventsLink: '/customer/browse-events' }, loadComponent: () => import('./features/public/detail/detail').then((m) => m.DetailComponent) },
      { path: 'bookings', title: 'My Bookings', loadComponent: () => import('./features/customer/bookings/customer-bookings').then((m) => m.CustomerBookingsComponent) },
      { path: 'services', title: 'Smart Services', loadComponent: () => import('./features/customer/smart-services/smart-services').then((m) => m.SmartServicesComponent) },
      { path: 'tickets', title: 'My Tickets', loadComponent: () => import('./features/customer/tickets/tickets').then((m) => m.TicketsComponent) },
      { path: 'parking', title: 'Parking', loadComponent: () => import('./features/customer/parking/parking').then((m) => m.ParkingComponent) },
      { path: 'food', title: 'Food', loadComponent: () => import('./features/customer/food/customer-food').then((m) => m.CustomerFoodComponent) },
      { path: 'places', title: 'Place Finder', loadComponent: () => import('./features/customer/places/place-finder').then((m) => m.PlaceFinderComponent) },
      { path: 'notifications', title: 'Notifications', loadComponent: () => import('./features/notifications/notifications').then((m) => m.NotificationsComponent) },
      { path: 'profile', title: 'Profile', loadComponent: () => import('./features/account/account-settings/account-settings').then((m) => m.AccountSettingsComponent) },
      { path: 'settings', title: 'Settings', loadComponent: () => import('./features/account/account-settings/account-settings').then((m) => m.AccountSettingsComponent) },
      { path: 'seats', title: 'Seat Selection', loadComponent: () => import('./features/customer/seat-selection/seat-selection').then((m) => m.SeatSelectionComponent) },
      { path: 'payment', title: 'Payment', loadComponent: () => import('./features/customer/payment/payment').then((m) => m.PaymentComponent) },
    ],
  },
  {
    path: 'organizer',
    canActivate: [authGuard, roleGuard],
    data: { role: 'organizer', roles: ['EventOrganizer'] },
    loadComponent: () => import('./layout/workspace-layout/workspace-layout').then((m) => m.WorkspaceLayoutComponent),
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', title: 'Organizer Dashboard', loadComponent: () => import('./features/organizer/dashboard/organizer-dashboard').then((m) => m.OrganizerDashboardComponent) },
      { path: 'events', title: 'Organizer Events', loadComponent: () => import('./features/organizer/events/organizer-events').then((m) => m.OrganizerEventsComponent) },
      { path: 'create-event', title: 'Create Event', loadComponent: () => import('./features/organizer/event-builder/event-builder').then((m) => m.EventBuilderComponent) },
      { path: 'events/:eventId/edit', title: 'Edit Event', loadComponent: () => import('./features/organizer/event-builder/event-builder').then((m) => m.EventBuilderComponent) },
      { path: 'events/:eventId/stage', title: 'Stage Setup', data: { step: 'stage' }, loadComponent: () => import('./features/organizer/event-setup/event-setup').then((m) => m.OrganizerEventSetupComponent) },
      { path: 'events/:eventId/seating', title: 'Seating Layout', data: { step: 'seating' }, loadComponent: () => import('./features/organizer/event-setup/event-setup').then((m) => m.OrganizerEventSetupComponent) },
      { path: 'events/:eventId/categories', title: 'Seat Categories', data: { step: 'categories' }, loadComponent: () => import('./features/organizer/event-setup/event-setup').then((m) => m.OrganizerEventSetupComponent) },
      { path: 'events/:eventId/preview', title: 'Event Preview', data: { step: 'preview' }, loadComponent: () => import('./features/organizer/event-setup/event-setup').then((m) => m.OrganizerEventSetupComponent) },
      { path: 'events/:eventId/media', title: 'Event Media', loadComponent: () => import('./features/organizer/event-media/event-media').then((m) => m.OrganizerEventMediaComponent) },
      { path: 'events/:eventId/seat-tools', title: 'Seat Tools & 360 Views', loadComponent: () => import('./features/organizer/seat-tools/seat-tools').then((m) => m.OrganizerSeatToolsComponent) },
      { path: 'venues', title: 'Organizer Venues', data: { kind: 'venues', workspace: true, detailBase: '/organizer/venues', backLink: '/organizer/create-event' }, loadComponent: () => import('./features/public/catalog/catalog').then((m) => m.CatalogComponent) },
      { path: 'venues/:slug', title: 'Venue Details', data: { kind: 'venue', backLink: '/organizer/venues', eventsLink: '/organizer/events' }, loadComponent: () => import('./features/public/detail/detail').then((m) => m.DetailComponent) },
      { path: 'bookings', redirectTo: 'events', pathMatch: 'full' },
      { path: 'seating', redirectTo: 'events', pathMatch: 'full' },
      { path: 'categories', redirectTo: 'events', pathMatch: 'full' },
      { path: 'tickets', redirectTo: 'events', pathMatch: 'full' },
      { path: 'payment-qr', title: 'Payment QR', data: { ownerLabel: 'Event Organizer' }, loadComponent: () => import('./features/shared/payment-qr/payment-qr').then((m) => m.PaymentQrComponent) },
      { path: 'venue-payments', title: 'Venue Payments', loadComponent: () => import('./features/organizer/venue-payments/venue-payments').then((m) => m.OrganizerVenuePaymentsComponent) },
      { path: 'payment-reviews', title: 'Payment Reviews', loadComponent: () => import('./features/shared/payment-review/payment-review').then((m) => m.PaymentReviewComponent) },
      { path: 'qr-checkin', title: 'QR Check-in', loadComponent: () => import('./features/admin/qr-checkin/qr-checkin').then((m) => m.QrCheckinComponent) },
      { path: 'reports', title: 'Analytics & Finance', loadComponent: () => import('./features/organizer/insights/organizer-insights').then((m) => m.OrganizerInsightsComponent) },
      { path: 'finance', redirectTo: 'reports', pathMatch: 'full' },
      { path: 'notifications', title: 'Notifications', loadComponent: () => import('./features/notifications/notifications').then((m) => m.NotificationsComponent) },
      { path: 'settings', title: 'Settings', loadComponent: () => import('./features/account/account-settings/account-settings').then((m) => m.AccountSettingsComponent) },
    ],
  },
  {
    path: 'venue-owner',
    canActivate: [authGuard, roleGuard],
    data: { role: 'venue-owner', roles: ['VenueOwner'] },
    loadComponent: () => import('./layout/workspace-layout/workspace-layout').then((m) => m.WorkspaceLayoutComponent),
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', title: 'Venue Owner Dashboard', loadComponent: () => import('./features/venue-owner/dashboard/venue-owner-dashboard').then((m) => m.VenueOwnerDashboardComponent) },
      { path: 'venues', title: 'My Venues', loadComponent: () => import('./features/venue-owner/venues/venue-owner-venues').then((m) => m.VenueOwnerVenuesComponent) },
      { path: 'venues/new', title: 'Register Venue', loadComponent: () => import('./features/venue-owner/venue-form/venue-form').then((m) => m.VenueFormComponent) },
      { path: 'venues/:id/edit', title: 'Edit Venue', loadComponent: () => import('./features/venue-owner/venue-form/venue-form').then((m) => m.VenueFormComponent) },
      { path: 'marketplace', title: 'Venue Marketplace', loadComponent: () => import('./features/venue-owner/marketplace/venue-marketplace').then((m) => m.VenueMarketplaceComponent) },
      { path: 'rentals', title: 'Venue Rentals', loadComponent: () => import('./features/venue-owner/rentals/venue-rentals').then((m) => m.VenueRentalsComponent) },
      { path: 'availability', title: 'Venue Availability', loadComponent: () => import('./features/venue-owner/availability/venue-availability').then((m) => m.VenueAvailabilityComponent) },
      { path: 'parking', title: 'Venue Parking', loadComponent: () => import('./features/venue-owner/parking/venue-parking').then((m) => m.VenueParkingComponent) },
      { path: 'payment-qr', title: 'Payment QR', data: { ownerLabel: 'Venue Owner' }, loadComponent: () => import('./features/shared/payment-qr/payment-qr').then((m) => m.PaymentQrComponent) },
      { path: 'reports', title: 'Venue Reports', loadComponent: () => import('./features/venue-owner/reports/venue-reports').then((m) => m.VenueReportsComponent) },
      { path: 'notifications', title: 'Notifications', loadComponent: () => import('./features/notifications/notifications').then((m) => m.NotificationsComponent) },
      { path: 'settings', title: 'Settings', loadComponent: () => import('./features/account/account-settings/account-settings').then((m) => m.AccountSettingsComponent) },
    ],
  },
  {
    path: 'admin',
    canActivate: [authGuard, roleGuard],
    data: { role: 'admin', roles: ['Admin'] },
    loadComponent: () => import('./layout/workspace-layout/workspace-layout').then((m) => m.WorkspaceLayoutComponent),
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', title: 'Admin Dashboard', loadComponent: () => import('./features/admin/dashboard/admin-dashboard').then((m) => m.AdminDashboardComponent) },
      { path: 'events', title: 'Event Management', data: { page: 'adminEvents' }, loadComponent: () => import('./features/workspace-page/workspace-page').then((m) => m.WorkspacePageComponent) },
      { path: 'event-categories', title: 'Event Categories', loadComponent: () => import('./features/admin/event-categories/event-categories').then((m) => m.EventCategoriesComponent) },
      { path: 'venue-facilities', title: 'Venue Facilities', loadComponent: () => import('./features/admin/venue-facilities/venue-facilities').then((m) => m.VenueFacilitiesComponent) },
      { path: 'nearby-places', title: 'Nearby Places', loadComponent: () => import('./features/admin/places/admin-places').then((m) => m.AdminPlacesComponent) },
      { path: 'audit-logs', title: 'Audit Logs', loadComponent: () => import('./features/admin/audit-logs/admin-audit-logs').then((m) => m.AdminAuditLogsComponent) },
      { path: 'receipt-delivery', title: 'Receipt Delivery', loadComponent: () => import('./features/admin/receipt-delivery/receipt-delivery').then((m) => m.AdminReceiptDeliveryComponent) },
      { path: 'venues', title: 'Venue Management', data: { page: 'adminVenues' }, loadComponent: () => import('./features/workspace-page/workspace-page').then((m) => m.WorkspacePageComponent) },
      { path: 'bookings', redirectTo: 'reports', pathMatch: 'full' },
      { path: 'payments', title: 'Payment Reviews', loadComponent: () => import('./features/shared/payment-review/payment-review').then((m) => m.PaymentReviewComponent) },
      { path: 'users', title: 'Users', loadComponent: () => import('./features/admin/users/admin-users').then((m) => m.AdminUsersComponent) },
      { path: 'seating-tickets', redirectTo: 'qr-checkin', pathMatch: 'full' },
      { path: 'qr-checkin', title: 'QR Check-in', loadComponent: () => import('./features/admin/qr-checkin/qr-checkin').then((m) => m.QrCheckinComponent) },
      { path: 'reports', title: 'Admin Reports', data: { page: 'adminReports' }, loadComponent: () => import('./features/workspace-page/workspace-page').then((m) => m.WorkspacePageComponent) },
      { path: 'operations', title: 'Operations', data: { page: 'operations' }, loadComponent: () => import('./features/workspace-page/workspace-page').then((m) => m.WorkspacePageComponent) },
      { path: 'notifications', title: 'Notifications', loadComponent: () => import('./features/notifications/notifications').then((m) => m.NotificationsComponent) },
      { path: 'settings', title: 'Settings', loadComponent: () => import('./features/account/account-settings/account-settings').then((m) => m.AccountSettingsComponent) },
    ],
  },
  { path: '**', title: 'Page Not Found', loadComponent: () => import('./features/public/not-found/not-found').then((m) => m.NotFoundComponent) },
];
