import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { SeoService } from '../../../core/services/seo.service';
import { RevealOnScrollDirective } from '../../../shared/directives/reveal-on-scroll.directive';

interface StaticSection { icon:string; title:string; copy:string; path?:string; }
@Component({selector:'app-static-page',imports:[RouterLink, RevealOnScrollDirective],templateUrl:'./static-page.html',styleUrl:'./static-page.scss'})
export class StaticPageComponent implements OnInit {
  private readonly route=inject(ActivatedRoute); private readonly seo=inject(SeoService);
  readonly mode=(this.route.snapshot.data['mode']??'services') as 'services'|'resources'|'about';
  readonly content={
    services:{eyebrow:'Nvent services',title:'Specialized experiences. One coherent platform.',copy:'Explore the customer and operational experiences that Nvent brings together in one platform.',sections:[{icon:'◇',title:'Event discovery',copy:'Search, filter, details, booking calls-to-action and role-aware journeys.',path:'/events'},{icon:'▦',title:'Venue discovery',copy:'Responsive venue media, details and event association.',path:'/venues'},{icon:'▥',title:'Seating & tickets',copy:'2D seat selection, optional 360 metadata, ticket and QR integration.',path:'/customer/seats'},{icon:'P',title:'Smart parking',copy:'Reservation, recommendation, navigation and status presentation.',path:'/customer/parking'},{icon:'◌',title:'Food discovery',copy:'Order food around supported events and follow the order from placement to fulfilment.',path:'/customer/food'},{icon:'⌖',title:'Place finder',copy:'Touch-friendly nearby-place discovery for couples, solo visitors, friends and families.',path:'/customer/places'}] as StaticSection[]},
    resources:{eyebrow:'Resources',title:'Useful guidance, without invented production facts.',copy:'Nvent support content is designed for clarity. Real policies, addresses and operational instructions must be supplied before launch.',sections:[{icon:'?',title:'Booking guidance',copy:'Understand the intended booking, ticket and arrival flow.'},{icon:'▤',title:'Ticket help',copy:'Get help with ticket status, QR use and check-in.'},{icon:'▥',title:'Seat selection help',copy:'Learn the meaning of available, selected, held, booked and unavailable.'},{icon:'P',title:'Arrival guidance',copy:'Parking and navigation guidance appears when venue information is available.'},{icon:'◎',title:'Accessibility',copy:'Keyboard, contrast, focus and non-colour state communication are built into the design.'},{icon:'⚙',title:'Account support',copy:'Manage sign-in and account support securely.'}] as StaticSection[]},
    about:{eyebrow:'About Nvent',title:'A premium event experience built around clear responsibilities.',copy:'Nvent brings event discovery, venue hosting, booking and event operations into one connected experience.',sections:[{icon:'✦',title:'Polished by design',copy:'Bright surfaces, teal emphasis, purposeful motion and restrained depth.'},{icon:'↔',title:'Built to integrate',copy:'Clear service boundaries keep the experience reliable and easy to extend.'},{icon:'◎',title:'Accessible by default',copy:'Keyboard access, strong focus, touch targets and reduced-motion behavior.'},{icon:'▦',title:'Responsive intentionally',copy:'Layouts adapt across desktop, laptop, tablet and narrow mobile screens.'},{icon:'⌁',title:'Operationally readable',copy:'Dense admin, finance and table screens prioritize information over spectacle.'},{icon:'◇',title:'Ready to extend',copy:'Seating, tickets and arrival services are organized so the platform can grow without disrupting existing journeys.'}] as StaticSection[]}
  }[this.mode];
  ngOnInit():void{this.seo.setPage(this.content.title,this.content.copy);}
}
