import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NearbyPlaceDto, VenueSummary } from '../../../core/models/api.models';
import { DomainApiService } from '../../../core/services/domain-api.service';
import { httpErrorMessage } from '../../../core/utils/http-error';
import { LocationMapComponent, MapLocationSelection, PlatformMapPin } from '../../../shared/components/location-map/location-map';
@Component({selector:'app-admin-places',imports:[FormsModule,LocationMapComponent],templateUrl:'./admin-places.html',styleUrl:'./admin-places.scss'})
export class AdminPlacesComponent implements OnInit{
 private readonly domain=inject(DomainApiService);readonly venues=signal<VenueSummary[]>([]);readonly places=signal<NearbyPlaceDto[]>([]);readonly loading=signal(true);readonly busy=signal(false);readonly error=signal('');readonly success=signal('');venueId='';editingId='';name='';category='Restaurant';tags='';audiences='Friends,Family';address='';distanceKm=1;latitude=0;longitude=0;isOpen=true;directionsUrl='';isActive=true;
 readonly mapPins=computed<PlatformMapPin[]>(()=>[...this.venues().filter(v=>v.latitude!=null&&v.longitude!=null).map(v=>({id:v.venueId??v.id??v.name,name:v.name,latitude:Number(v.latitude),longitude:Number(v.longitude),kind:'venue' as const,subtitle:v.city})),...this.places().map(p=>({id:p.id,name:p.name,latitude:p.latitude,longitude:p.longitude,kind:'place' as const,subtitle:p.category}))]);
 ngOnInit():void{this.domain.venues().subscribe({next:v=>{this.venues.set(v);this.venueId=v[0]?.venueId??v[0]?.id??'';this.load();},error:e=>{this.loading.set(false);this.error.set(httpErrorMessage(e,'Venues could not be loaded.'));}});} load():void{if(!this.venueId){this.loading.set(false);return;}this.loading.set(true);this.domain.places(this.venueId,{includeClosed:true}).subscribe({next:p=>{this.places.set(p);this.loading.set(false);},error:e=>{this.loading.set(false);this.error.set(httpErrorMessage(e,'Nearby places could not be loaded.'));}});}
 selectedVenue():VenueSummary|undefined{return this.venues().find(v=>(v.venueId??v.id)===this.venueId);} edit(p:NearbyPlaceDto):void{this.editingId=p.id;this.name=p.name;this.category=p.category;this.tags=p.tags.join(',');this.audiences=p.audienceModes.join(',');this.address=p.address;this.distanceKm=p.distanceKm;this.latitude=p.latitude;this.longitude=p.longitude;this.isOpen=p.isOpen;this.directionsUrl=p.directionsUrl??'';window.scrollTo({top:0,behavior:'smooth'});} reset():void{this.editingId='';this.name='';this.category='Restaurant';this.tags='';this.audiences='Friends,Family';this.address='';this.distanceKm=1;this.latitude=0;this.longitude=0;this.isOpen=true;this.directionsUrl='';}
 point(location:MapLocationSelection):void{this.latitude=location.latitude;this.longitude=location.longitude;this.address=location.displayName||[location.addressLine1,location.city,location.country].filter(Boolean).join(', ')||this.address;this.directionsUrl=`https://www.openstreetmap.org/?mlat=${location.latitude}&mlon=${location.longitude}#map=17/${location.latitude}/${location.longitude}`;const v=this.selectedVenue();if(v?.latitude!=null&&v?.longitude!=null)this.distanceKm=Number(this.haversine(Number(v.latitude),Number(v.longitude),location.latitude,location.longitude).toFixed(2));}
 save():void{if(!this.venueId||!this.name.trim()||!this.address.trim()||this.busy())return;const body={venueId:this.venueId,name:this.name.trim(),category:this.category,tags:this.tags.split(',').map(x=>x.trim()).filter(Boolean),audienceModes:this.audiences.split(',').map(x=>x.trim()).filter(Boolean),address:this.address.trim(),distanceKm:Number(this.distanceKm),latitude:Number(this.latitude),longitude:Number(this.longitude),isOpen:this.isOpen,directionsUrl:this.directionsUrl.trim()||null,isActive:this.isActive};this.busy.set(true);const req=this.editingId?this.domain.updatePlace(this.editingId,body):this.domain.createPlace(body);req.subscribe({next:()=>{this.busy.set(false);this.success.set(this.editingId?'Place updated.':'Place added.');this.reset();this.load();},error:e=>{this.busy.set(false);this.error.set(httpErrorMessage(e,'The place could not be saved.'));}});} remove(p:NearbyPlaceDto):void{if(this.busy()||!confirm(`Remove ${p.name}?`))return;this.busy.set(true);this.domain.deletePlace(p.id).subscribe({next:()=>{this.busy.set(false);this.load();},error:e=>{this.busy.set(false);this.error.set(httpErrorMessage(e,'The place could not be removed.'));}});}
 private haversine(a:number,b:number,c:number,d:number):number{const r=6371,rad=(x:number)=>x*Math.PI/180;const x=rad(c-a),y=rad(d-b),q=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return 2*r*Math.asin(Math.sqrt(q));}
}
