import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { BookingSummary, EventSummary, ParkingReservationDto, ParkingSlotDto, ParkingZoneDto, SavedVehicleDto } from '../../../core/models/api.models';
import { DomainApiService } from '../../../core/services/domain-api.service';
import { httpErrorMessage } from '../../../core/utils/http-error';

@Component({selector:'app-parking',imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./parking.html',styleUrl:'./parking.scss'})
export class ParkingComponent implements OnInit{
 private readonly domain=inject(DomainApiService); private readonly route=inject(ActivatedRoute);
 readonly bookings=signal<BookingSummary[]>([]); readonly event=signal<EventSummary|null>(null); readonly vehicles=signal<SavedVehicleDto[]>([]); readonly zones=signal<ParkingZoneDto[]>([]); readonly slots=signal<ParkingSlotDto[]>([]); readonly reservation=signal<ParkingReservationDto|null>(null); readonly loading=signal(true); readonly error=signal(''); readonly success=signal(''); readonly busy=signal(false);
 bookingId='';zoneId='';slotId='';vehicleId='';vehicleRegistration='';nickname='My vehicle';vehicleType='Car';requiresAccessible=false;editingVehicleId='';
 ngOnInit():void{this.load();}
 load():void{this.loading.set(true);this.error.set('');this.domain.bookings().subscribe({next:b=>{this.bookings.set(b.filter(x=>['Confirmed','Completed'].includes(this.status(x.status))));const q=this.route.snapshot.queryParamMap.get('bookingId');this.bookingId=(q&&this.bookings().some(x=>this.bid(x)===q))?q:this.bid(this.bookings()[0]);this.domain.vehicles().subscribe({next:v=>{this.vehicles.set(v);this.vehicleId=v.find(x=>x.isDefault)?.id??v[0]?.id??'';this.vehicleRegistration=v.find(x=>x.id===this.vehicleId)?.registrationNo??'';this.loadBookingContext();},error:()=>this.loadBookingContext()});},error:e=>{this.loading.set(false);this.error.set(httpErrorMessage(e,'Your bookings could not be loaded.'));}});}
 bid(b?:BookingSummary):string{return b?.bookingId??b?.id??'';}
 status(v:string|number|undefined):string{return typeof v==='number'?(['Pending','Confirmed','Cancelled','Completed'][v]??String(v)):(v||'');}
 loadBookingContext():void{const b=this.bookings().find(x=>this.bid(x)===this.bookingId);if(!b?.eventId){this.loading.set(false);this.event.set(null);return;}this.loading.set(true);this.domain.event(b.eventId).subscribe({next:e=>{this.event.set(e);const venueId=e.venueId??'';if(!venueId){this.loading.set(false);return;}this.domain.parkingZones(venueId).subscribe({next:z=>{this.zones.set(z);this.zoneId=z[0]?.id??'';this.loadSlots();this.loadStoredReservation();},error:err=>{this.loading.set(false);this.error.set(httpErrorMessage(err,'Parking information could not be loaded.'));}});},error:err=>{this.loading.set(false);this.error.set(httpErrorMessage(err,'Event information could not be loaded.'));}});}
 loadSlots():void{this.slots.set([]);this.slotId='';if(!this.zoneId){this.loading.set(false);return;}this.loading.set(true);this.domain.parkingSlots(this.zoneId).subscribe({next:s=>{this.slots.set(s.filter(x=>x.status==='Available'&&(!this.requiresAccessible||x.isAccessible)));this.slotId=this.slots()[0]?.id??'';this.loading.set(false);},error:e=>{this.loading.set(false);this.error.set(httpErrorMessage(e,'Parking spaces could not be loaded.'));}});}
 onVehicle():void{const vehicle=this.vehicles().find(x=>x.id===this.vehicleId);this.vehicleRegistration=vehicle?.registrationNo??'';this.nickname=vehicle?.nickname??'My vehicle';this.vehicleType=vehicle?.vehicleType??'Car';this.editingVehicleId=vehicle?.id??'';}
 saveVehicle():void{if(!this.vehicleRegistration.trim()||this.busy())return;this.busy.set(true);this.error.set('');const body={nickname:this.nickname.trim()||'My vehicle',registrationNo:this.vehicleRegistration.trim(),vehicleType:this.vehicleType,isDefault:this.editingVehicleId?(this.vehicles().find(x=>x.id===this.editingVehicleId)?.isDefault??false):this.vehicles().length===0};const request=this.editingVehicleId?this.domain.updateVehicle(this.editingVehicleId,body):this.domain.createVehicle(body);request.subscribe({next:v=>{this.busy.set(false);this.vehicles.set(this.editingVehicleId?this.vehicles().map(x=>x.id===v.id?v:x):[...this.vehicles(),v]);this.vehicleId=v.id;this.editingVehicleId=v.id;this.success.set('Vehicle saved.');},error:e=>{this.busy.set(false);this.error.set(httpErrorMessage(e,'The vehicle could not be saved.'));}});}
 removeVehicle():void{const id=this.editingVehicleId;if(!id||this.busy()||!confirm('Remove this saved vehicle?'))return;this.busy.set(true);this.domain.deleteVehicle(id).subscribe({next:()=>{this.busy.set(false);this.vehicles.set(this.vehicles().filter(x=>x.id!==id));this.vehicleId='';this.editingVehicleId='';this.vehicleRegistration='';this.nickname='My vehicle';this.vehicleType='Car';this.success.set('Vehicle removed.');},error:e=>{this.busy.set(false);this.error.set(httpErrorMessage(e,'The vehicle could not be removed.'));}});}
 newVehicle():void{this.vehicleId='';this.editingVehicleId='';this.vehicleRegistration='';this.nickname='My vehicle';this.vehicleType='Car';}
 reserve():void{if(!this.bookingId||!this.slotId||!this.vehicleRegistration.trim()||this.busy())return;this.busy.set(true);this.error.set('');this.success.set('');this.domain.createParkingReservation({bookingId:this.bookingId,parkingSlotId:this.slotId,vehicleId:this.vehicleId||null,vehicleRegistration:this.vehicleRegistration.trim()}).subscribe({next:r=>{this.busy.set(false);this.reservation.set(r);if(typeof localStorage!=='undefined')localStorage.setItem(`nvent.parking.${this.bookingId}`,r.id);this.success.set('Parking reserved. Your arrival status is ready below.');this.loadSlots();},error:e=>{this.busy.set(false);this.error.set(httpErrorMessage(e,'Parking could not be reserved.'));}});}
 transition(kind:'enter'|'park'|'exit'):void{const r=this.reservation();if(!r||this.busy())return;this.busy.set(true);const call=kind==='enter'?this.domain.parkingEnter(r.id):kind==='park'?this.domain.parkingPark(r.id):this.domain.parkingExit(r.id);call.subscribe({next:v=>{this.busy.set(false);this.reservation.set(v);},error:e=>{this.busy.set(false);this.error.set(httpErrorMessage(e,'Parking status could not be updated.'));}});}
 cancelReservation():void{const r=this.reservation();if(!r||this.busy()||!confirm('Cancel this parking reservation?'))return;this.busy.set(true);this.domain.cancelParkingReservation(r.id).subscribe({next:()=>{this.busy.set(false);this.reservation.set(null);if(typeof localStorage!=='undefined')localStorage.removeItem(`nvent.parking.${this.bookingId}`);this.loadSlots();},error:e=>{this.busy.set(false);this.error.set(httpErrorMessage(e,'Parking reservation could not be cancelled.'));}});}
 private loadStoredReservation():void{if(typeof localStorage==='undefined'||!this.bookingId)return;const id=localStorage.getItem(`nvent.parking.${this.bookingId}`);if(!id)return;this.domain.parkingReservation(id).subscribe({next:r=>this.reservation.set(r),error:()=>localStorage.removeItem(`nvent.parking.${this.bookingId}`)});}
}
